# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-pg" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "410b9d1193da8f04c3a3d7ca4fd8e5e0d7d95f14de1576290339b15cf03c2fe4"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-pg_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f40c77e67f6200389f1a5ebc7e562947d96bb843f35a53df1a4756f9d16d88f"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-pg_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "219c5a72b3619e31c25835735579399a4003d4dea119aa13f8415f95838f457d"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-pg_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8bd334e22c8a315ae2a9bfdf3fd8f6f76e7ce06ce4f7589307fd83b6131bf344"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-pg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-pg"
  desc "Atelier tool — Postgres pgcli launcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "pgcli",
    ]

  binary "atelier-pg"

  # No zap stanza required

end
