# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "7cc6bcffe6a85a1f37ddea8688ab05a97f8a6dd5158d9911b30e80f1562e2d3d"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "769b998f7b4adc0fb0f3333065428fa3d46d3cdc6d1260e900e1b97404966d5d"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a62086fa2dddeda0bfd0fa39e009d3be8f97f0b1f08fe8a75f5db755b2deaf86"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "982dd09712644722a3f3da40a43ae414065d8679d302acca3430dbb34e342979"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier"
  desc "TUI-native agentic workspaces — one binary, tmux-driven"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
      "tmux",
    ]

  binary "atelier"

  # No zap stanza required

end
