# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-popupshell" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cf85efc92e838026ffc6954d1e9c8ae22e90de9a9917725e74bbaabf843bf68a"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-popupshell_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "844a4a872b13133633bf2b6ebe76559033d17538412029773956639d1fc021b6"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-popupshell_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d52a78f783629dbaf7fe75f5b5a867ad71c2de431b6df53913213f810468c59"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-popupshell_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "11e5969315307cd8be6ccb27710fb7846f034e7a5c19383dab2c62d8e46ebf5b"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-popupshell_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-popupshell"
  desc "Atelier tool — popup shell"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ]

  binary "atelier-popupshell"

  # No zap stanza required

end
