# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-toolselector" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4e2b4bf089cac113afe57484cafd02c2d5deef9693d06dafb40b9afa207934df"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-toolselector_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "61c2694ecc379ac3324e1c4193b2ad50e8ba376b2b497894e01438bcb0c2aa54"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-toolselector_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57b48511ac2033bdd8088db6fd5f3d0c887b8db07279a633b983a6b6e52b07a3"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-toolselector_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "71c70e74102d0083aa355e65f7af17948a02f9a4c9bee5534676e4e4eb159d31"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-toolselector_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-toolselector"
  desc "Atelier tool — M-; tool picker"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ]

  binary "atelier-toolselector"

  # No zap stanza required

end
