# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "34a18019e29ec3f4bd14826a692012494e3530b66f713e2235dd4603d81e103b"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4b84cf78467600d4b59c5102ce83bd21258c253577a731cc3ec8bae1ce08ff33"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e68f1694395ec50abb01a7436a9847009dffe4534e00df1b7665cacc3cc7a74a"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0835297125d8b23f7bcf2ffbefae11673f08ec04ad4ed36fd3d9dad507a0203b"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier"
  desc "TUI-native agentic workspaces — one binary, tmux-driven"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
      "tmux",
    ]

  binary "atelier"

  # No zap stanza required

end
