# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-claude" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "05e4e8e26e0a3e2322687c0be76f30441acd8e55c0394902ac57e83853baff13"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-claude_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b835b930a8c003d86384e8a663d230d78fcf71e72b289d81ad715136269d385c"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-claude_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b173349b3c159a453827c516989ffae0fd66fd807a3472ffeaf230cd819a86cd"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-claude_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d465860eaf86b94d034d17cb67b8890beddde749eb54eb7722ba8c564ecbc9b1"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-claude_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-claude"
  desc "Atelier tool — Claude Code integration"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ]

  binary "atelier-claude"

  # No zap stanza required

end
