# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-aws" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e455c0c13534630e6638891c02785230907b299cceab512f3e0398dffda181e1"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-aws_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a7ba837eadc6f1a4c5cf99626a9c2c7c2d2e5a123283965889c96be7778aa4cf"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-aws_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6fe8dd2cdabad2c3200ac8a5b4738740b09e32ba609aaf39dead14735ee842e"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-aws_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2e5cfcc3907341419d36ad5536a306f3778aa175bb01d886441f69714cf85028"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-aws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-aws"
  desc "Atelier tool — AWS context switcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "awscli",
    ]

  binary "atelier-aws"

  # No zap stanza required

end
