# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-ghdash" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2d8f1e942b3fc9e5ef88944e9d8c234d4c47cf09bdfabb7755101e2b4b60d210"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghdash_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b1b1f686b4934e7491c62c6ea4fab981eba4e26221fd3f66159a33a071ead2dd"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghdash_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5909655b7ca3ed6dc16f96eb4edcfcfce45c7418f9afe969f6fd686dcadf7c6f"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghdash_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7c7af0554b8cda2f2fb5e64cebccb4877ab18d6f39f4b26aa8d04c86e5d95002"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghdash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-ghdash"
  desc "Atelier tool — gh-dash PR dashboard launcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "gh",
    ]

  binary "atelier-ghdash"

  # No zap stanza required

end
