# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-ghenhance" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "572a1fa123c5f246a628576aa23e4c9115dc7b35fee512366a19a411165fa8da"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghenhance_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1828ef5eee13ba1f5ed56c70632ff9ade775148973c59aa57eaec6ab78d50ed4"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghenhance_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "feef648461ebc83025d155d5b693ef6611d551f4f295f7d384897d3ddac7684b"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghenhance_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1ac95edafc3fe313f6cee55795edced40aa78fbc74872f66b911713d27d95ea5"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ghenhance_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-ghenhance"
  desc "Atelier tool — gh enhance-repo launcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "gh",
    ]

  binary "atelier-ghenhance"

  # No zap stanza required

end
