# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-lazygit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ed096db1107027b43770bb6fa6f08d4a1cede5f83a7a66eba8e78aa2c98343ac"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-lazygit_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "953eec8d56599c237082c7793ece89956c4fbed6e8ed991d096d0d1348a217c1"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-lazygit_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7aa644d76b5818cff2165434db10416aa89d126d5ccbcbc57ad9b3f7c103aedc"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-lazygit_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "060806fb1c451b1b74b35180b0192594f6816e8d1120592b1c664fc820c3feba"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-lazygit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-lazygit"
  desc "Atelier tool — lazygit launcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "lazygit",
    ]

  binary "atelier-lazygit"

  # No zap stanza required

end
