# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-workspaces" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "27ee30825fad7b04cb219b4f5fcdf35c04d1cc6e67da53b2a68ad7b6e15ab6b5"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-workspaces_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a73b46065bf9e7222fe9cd512f93ccab6263c68ae24c0f362ffa6f0f6175c6bd"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-workspaces_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67e934b7ebe5afa3f7fb528ee945e01eae6ed502f750738d75aa927ac68bc98a"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-workspaces_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "871049e6e79a27ed6fe59dd9ac399a7d27b53dd81b1981610d6e3b8527e3cdfe"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-workspaces_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-workspaces"
  desc "Atelier tool — workspace + worktree manager"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ]

  binary "atelier-workspaces"

  # No zap stanza required

end
