# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-k8s" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "426afdeed1aabade6581e230ec1467cccb16f8db7c1ad1c25d2fbb8ce999ea72"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-k8s_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b3fb32f188d99fc782f2a4682e577c01a7e6ee6fe5bc7c7edbb215c65393fd74"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-k8s_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66f595b251836a549a434c561bbb690c1cf3af31f5278bb0e4122367abd0131c"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-k8s_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2ef0167402c5fc4c46d70db09567e81ad19fee9a1be46bced5f93f2f05f57c29"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-k8s_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-k8s"
  desc "Atelier tool — k9s + EKS context switcher"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "k9s",
    ]

  binary "atelier-k8s"

  # No zap stanza required

end
