# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "db7140d97504559b5203951ae861f0e150cb1af71e49816c1977f45a4216d081"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2f5cc157cbe2f6168c94f66e1c448f118256da53dbd4fb582fe51cbed7f2f2ba"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a4ada10a1e38723f02fbf12707105d8a5cb2537222c1b7cdaf5c1c3cd40f00fc"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3ef0e92ad86375810a619b99ed53646713dee2517efee2b60d3a0c94670d39dd"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier"
  desc "TUI-native agentic workspaces — one binary, tmux-driven"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
      "tmux",
    ]

  binary "atelier"

  # No zap stanza required

end
