# This file was generated by GoReleaser. DO NOT EDIT.
cask "atelier-ccusage" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5fa4722acf323cf6fb716c2c34e6dec6f321f5e6e66eaf6fb199bdcef294945c"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ccusage_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0d0f68519d29ff383d1a4f1fea877289e184e2ffbb151f179e2342ff06e0a6e5"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ccusage_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "efb2a140ef0e74b3d24c66caed07cbb33fd975e5321e98ec64bc49ef2f349750"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ccusage_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a9802ee92e65a83435fc58e155420a91149bb4712c8f85a6913565f88a47fec8"
      url "https://github.com/vyrwu/atelier/releases/download/v#{version}/atelier-ccusage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atelier-ccusage"
  desc "Atelier tool — Claude API usage snapshot popup"
  homepage "https://github.com/vyrwu/atelier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "atelier",
    ],
    formula: [
      "node",
    ]

  binary "atelier-ccusage"

  # No zap stanza required

end
